arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]

c_compiler_version:
  - 10          # [linux and aarch64]
  - 10          # [linux and x86_64]

cxx_compiler_version:
  - 10          # [linux and aarch64]
  - 10          # [linux and x86_64]

fortran_compiler_version:
  - 10          # [linux and aarch64]
  - 10          # [linux and x86_64]

docker_image:
  # TODO: change me
  # We're using the CUDA 11.8 image, based on ubi8, only to get a
  # newer glibc. cuSPARSELt v0.4.0+ expects GLIBC_2.27.
  # xref: https://github.com/conda-forge/cudnn-feedstock/pull/56
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.8  # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-cuda:11.8          # [linux and x86_64]
