{% set version = "0.7.0.0" %}
{% set soversion = ".".join(version.split(".")[:4]) %}
{% set somajor = version.split(".")[0] %}
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "placeholder" %}  # [osx]
{% set extension = "tar.xz" %}  # [unix]
{% set platform = "windows-x86_64" %}  # [win64]
{% set extension = "zip" %}  # [win64]

{% set cuda_compiler_version = cuda_compiler_version|default("None") %}
{% set cuda_major = environ.get("cuda_compiler_version", "12.0").split(".")[0] %}

package:
  name: cusparselt-split
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}-archive.tar.xz  # [linux64]
    sha256: 6082f3d7f024b0183225d48361ca8436fdf30d5833e3595c6c145c03171c13ee  # [linux64]
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}-archive.tar.xz  # [aarch64]
    sha256: f625038f52dec7068824889d523e16112a2363c7e4f1da87adaac6db6bb7caa5  # [aarch64]
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}-archive.zip  # [win64]
    sha256: 06c2d7a7ef37f3a0fc124491ec9486de8f8f1fdfc25449e54b01840abbe19047  # [win64]

build:
  number: 1
  skip: true  # [ppc64le or not (cuda_compiler_version or "").startswith("12")]
  script:  # [win]
    - xcopy include %LIBRARY_INC% /E /I /Y /V  # [win]
    - copy lib\cusparseLt.lib %LIBRARY_LIB%\cusparseLt.lib /Y /V  # [win]
    - copy lib\cusparseLt.dll %LIBRARY_BIN%\cusparseLt.dll /Y /V  # [win]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1   # [linux]

outputs:

  - name: cusparselt
    build:
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    files:
      - lib/libcusparseLt.so.*              # [linux]
      - Library/bin/cusparseLt.dll          # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cuda') }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/lib/libcusparseLt.so.{{ soversion }}  # [linux]
        - test -L $PREFIX/lib/libcusparseLt.so.{{ somajor }}  # [linux]
        - test ! -f $PREFIX/lib/libcusparseLt_static.a  # [linux]
        - if not exist %LIBRARY_BIN%\\cusparseLt.dll exit 1  # [win]
    about:
      summary: The NVIDIA cuSPARSELt runtime library
      license: LicenseRef-cuSPARSELt-Software-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install cusparselt-dev to build with
        cuSPARSELt.

  - name: cusparselt-dev
    build:
      run_exports:
        # Breaking changes every version until 1.0
        - {{ pin_subpackage("cusparselt", max_pin="x.x.x") }}
    files:
      - lib/libcusparseLt.so    # [linux]
      - include/cusparseLt.h    # [linux]
      - Library/lib/cusparseLt.lib    # [win]
      - Library/include/cusparseLt.h  # [win]
    requirements:
      host:
        - {{ pin_subpackage("cusparselt", exact=True) }}
      run:
        - {{ pin_subpackage("cusparselt", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      files:
        - test/test_load_elf.c        # [linux]
        - test/run_test.sh   # [linux]
        - test/run_test.bat  # [win]
      commands:
        - test -f $PREFIX/include/cusparseLt.h  # [linux]
        - test -L $PREFIX/lib/libcusparseLt.so  # [linux]
        - test ! -f $PREFIX/lib/libcusparseLt_static.a  # [linux]
        - bash test/run_test.sh  # [linux]
        - if not exist %LIBRARY_LIB%\\cusparseLt.lib exit 1  # [win]
        - if not exist %LIBRARY_INC%\\cusparseLt.h exit 1  # [win]
        - test/run_test.bat  # [win]
      requires:  # [build_platform == target_platform]
        - {{ compiler("c") }}  # [build_platform == target_platform]
        - {{ compiler("cxx") }}  # [build_platform == target_platform]
        - {{ compiler('cuda') }}  # [build_platform == target_platform]
        - {{ stdlib("c") }}  # [build_platform == target_platform]
        - cmake  # [build_platform == target_platform]
        - ninja  # [build_platform == target_platform]
        - git
        # test_load_elf needs the cuSPARSE header & libnvrtc.so
        - libcusparse-dev        # [linux]
        - cuda-nvrtc-dev         # [linux]
        - cuda-driver-dev        # [linux and (cuda_compiler_version or "").startswith("12")]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a sparse matrix.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - kvoronin
    - mtjrider
    - mnicely
    - leofang
