{% set version = "0.9.1.1" %}
{% set soversion = ".".join(version.split(".")[:4]) %}
{% set somajor = version.split(".")[0] %}
{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

package:
  name: cusparselt-split
  version: {{ version }}

source:
  - url: "https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}_cuda13-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "e77c16595ce572fbd5d98c5a4959bb955055b5f8c339f5695430358e177360ff"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}_cuda13-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "542fcec45ea23b2cc805010e5f270088839af1c88f8c578e3113d6fb452d7564"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}_cuda13-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "2d018fcd0601f1812c38b7e13300c924a97458f2b3326bd6064a33e5bab05b33"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]

build:
  number: 0
  skip: true  # [ppc64le or not (cuda_compiler_version or "").startswith("13")]
  script:   # [win]
    - xcopy include %LIBRARY_INC% /E /I /Y /V  # [win]
    - copy lib\cusparseLt.lib %LIBRARY_LIB%\cusparseLt.lib /Y /V  # [win]
    - copy bin\cusparseLt.dll %LIBRARY_BIN%\cusparseLt.dll /Y /V  # [win]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1   # [linux]

outputs:

  - name: cusparselt
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libcusparseLt.so.*              # [linux]
      - Library/bin/cusparseLt.dll          # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cuda') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
    test:
      commands:
        - test -f $PREFIX/lib/libcusparseLt.so.{{ soversion }}  # [linux]
        - test -L $PREFIX/lib/libcusparseLt.so.{{ somajor }}  # [linux]
        - test ! -f $PREFIX/lib/libcusparseLt_static.a  # [linux]
        - if not exist %LIBRARY_BIN%\\cusparseLt.dll exit 1  # [win]
    about:
      summary: The NVIDIA cuSPARSELt runtime library
      license: LicenseRef-cuSPARSELt-Software-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install cusparselt-dev to build with cuSPARSELt.

  - name: cusparselt-dev
    build:
      run_exports:
        # Breaking changes every version until 1.0
        - {{ pin_subpackage("cusparselt", max_pin="x.x.x") }}
    files:
      - lib/libcusparseLt.so    # [linux]
      - include/cusparseLt.h    # [linux]
      - Library/lib/cusparseLt.lib    # [win]
      - Library/include/cusparseLt.h  # [win]
    requirements:
      host:
        - {{ pin_subpackage("cusparselt", exact=True) }}
      run:
        - {{ pin_subpackage("cusparselt", exact=True) }}
    test:
      files:
        - test/test_load_elf.c        # [linux]
        - test/run_test.sh   # [linux]
        - test/run_test.bat  # [win]
      commands:
        - test -f $PREFIX/include/cusparseLt.h  # [linux]
        - test -L $PREFIX/lib/libcusparseLt.so  # [linux]
        - test ! -f $PREFIX/lib/libcusparseLt_static.a  # [linux]
        - bash test/run_test.sh  # [linux]
        - if not exist %LIBRARY_LIB%\\cusparseLt.lib exit 1  # [win]
        - if not exist %LIBRARY_INC%\\cusparseLt.h exit 1  # [win]
        - test/run_test.bat  # [win]
      requires:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - git
        - libcusparse-dev # test_load_elf needs the cuSPARSE header & libnvrtc.s
        - cuda-nvrtc-dev
        - cuda-driver-dev  # [linux]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a structured sparse matrix
    with 50\% sparsity.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - kvoronin
    - mtjrider
    - mnicely
    - leofang
