{% set version = "0.6.3.2" %}

package:
  name: cusparselt
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}-archive.tar.xz  # [linux64]
    sha256: a2f856e78943f5c538bdef1c9edc64a5ed30bf8bb7d5fcb615c684ffe776cc31  # [linux64]
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}-archive.tar.xz  # [aarch64]
    sha256: 3e420ddbff4eb9ac603f57c7aa8b3d5271112816e244eb55ef9f30c4eb6a04b7  # [aarch64]
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}-archive.zip  # [win64]
    sha256: 6d276e33a399008c22ffefd707eefe2f57ff2ff8f1dc1929d9e3e75d3c83562d  # [win64]

build:
  number: 1
  skip: true  # [ppc64le or not (cuda_compiler_version or "").startswith("12")]
  script:
    - mkdir -p $PREFIX/include                                                # [unix]
    - cp -r include/* $PREFIX/include/                                        # [unix]
    - mkdir -p $PREFIX/lib                                                    # [unix]
    - mv lib/libcusparseLt.so* $PREFIX/lib/                                   # [unix]

    - copy include\\cusparseLt.h %LIBRARY_INC%\\                           # [win64]
    - copy lib\\cusparseLt.dll %LIBRARY_BIN%\\                             # [win64]
    - copy lib\\cusparseLt.lib %LIBRARY_LIB%\\                             # [win64]
  run_exports:
    - {{ pin_subpackage('cusparselt', max_pin='x.x.x.x') }}
  missing_dso_whitelist:
    - '*/libgomp.*'  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    # https://github.com/NixOS/patchelf/issues/492
    - patchelf !=0.18     # [linux]
  run:
  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [linux]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    # tests need the cuSPARSE header & libnvrtc.so
    - libcusparse-dev
    - cuda-nvrtc-dev
    - cuda-driver-dev        # [linux and (cuda_compiler_version or "").startswith("12")]
  files:
    - test_load_elf.c        # [linux]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a sparse matrix.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - kvoronin
    - mtjrider
    - mnicely
    - leofang
