{% set version = "0.7.1.0" %}

package:
  name: cusparselt
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}-archive.tar.xz  # [linux64]
    sha256: a0d885837887c73e466a31b4e86aaae2b7d0cc9c5de0d40921dbe2a15dbd6a88  # [linux64]
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}-archive.tar.xz  # [aarch64]
    sha256: 4a131d0a54728e53ba536b50bb65380603456f1656e7df8ee52e285618a0b57c  # [aarch64]
  - url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}-archive.zip  # [win64]
    sha256: 004bcb1b700c24ca8d60a8ddd2124640f61138a6c29914d2afaa0bfa0d0e3cf2  # [win64]

build:
  number: 0
  skip: true  # [ppc64le or not (cuda_compiler_version or "").startswith("12")]
  script:
    - check-glibc lib/*.so.*                                                  # [unix]
    - mkdir -p $PREFIX/include                                                # [unix]
    - cp -r include/* $PREFIX/include/                                        # [unix]
    - mkdir -p $PREFIX/lib                                                    # [unix]
    - mv lib/libcusparseLt.so* $PREFIX/lib/                                   # [unix]

    - copy include\\cusparseLt.h %LIBRARY_INC%\\                           # [win64]
    - copy lib\\cusparseLt.dll %LIBRARY_BIN%\\                             # [win64]
    - copy lib\\cusparseLt.lib %LIBRARY_LIB%\\                             # [win64]
  run_exports:
    - {{ pin_subpackage('cusparselt', max_pin='x.x.x.x') }}
  missing_dso_whitelist:
    - '*/libgomp.*'  # [linux]

requirements:
  build:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cf-nvidia-tools 1   # [linux]
      # https://github.com/NixOS/patchelf/issues/492
    - patchelf <0.18.0    # [linux]
  run:

test:
  requires:
    - git
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    # tests need the cuSPARSE header & libnvrtc.so
    - libcusparse-dev
    - cuda-nvrtc-dev
    - cuda-driver-dev        # [linux and (cuda_compiler_version or "").startswith("12")]
    - patchelf               # [linux]
  files:
    - test_load_elf.c        # [linux]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a sparse matrix.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - kvoronin
    - mtjrider
    - mnicely
    - leofang
