{% set version = "0.4.0.6" %}

package:
  name: cusparselt
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse-lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}-archive.tar.xz  # [linux64]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse-lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}-archive.tar.xz  # [aarch64]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse-lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}-archive.zip  # [win64]
  sha256: 41ed4fe763e394bd435d977051f0f1a0bd51aa782d0aa46555dd64c8077c2f26  # [linux64]
  sha256: b546f836b12a96c645095a087a1e216e48a0b720a816a355832ed79937bc20f5  # [aarch64]
  sha256: b972af965c4c98265c1bce42dfb97b19f67451db527589ea1bd504205b266413  # [win64]

build:
  number: 0
  skip: true  # [ppc64le or osx]
  script:
    - mkdir -p $PREFIX/include                                                # [unix]
    - cp -r include/* $PREFIX/include/                                        # [unix]
    - mkdir -p $PREFIX/lib                                                    # [unix]
    - mv lib/libcusparseLt.so* $PREFIX/lib/                                   # [unix]

    - copy include\\cusparseLt.h %LIBRARY_INC%\\                           # [win64]
    - copy lib\\cusparseLt.dll %LIBRARY_BIN%\\                             # [win64]
    - copy lib\\cusparseLt.lib %LIBRARY_LIB%\\                             # [win64]
  run_exports:
    - {{ pin_subpackage('cusparselt', exact=True) }}
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*/libgomp.*'  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # - {{ compiler('cuda') }}  # can't use nvcc here, due to version mismatch with the docker image
    - sysroot_{{ target_platform }} 2.17  # [linux]
  run:
    - cudatoolkit 11.*
  run_constrained:
    - __glibc >=2.27  # [linux]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - test_load_elf.c        # [linux]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a sparse matrix.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - mnicely
    - leofang
